project:
  alias: expeditor-acceptance


promote:
  channels:
    - dummy

merge_actions:
  - built_in:bump_version:
      ignore_labels:
        - "Version: Skip Bump"
  - bash:.expeditor/update_version.sh:
      only_if: built_in:bump_version
  - built_in:update_changelog:
      ignore_labels:
        - "Changelog: Skip Update"
  - trigger_pipeline:habitat/build

subscriptions:
  - workload: generic_workload_published:acceptance_tests:*
    actions:
      - bash:.expeditor/trigger_pr_merge_tests.sh
  - workload: buildkite_hab_build_group_published:{{agent_id}}:*
    actions:
      - built_in:promote_habitat_packages

